/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DjEngine {
  constructor()
  ping(): string
  getDecks(): Array<DeckState>
  getMixer(): MixerState
  getState(): EngineState
  getDeck(deckId: number): DeckState | null
  loadTrack(deckId: number, filePath: string): void
  toggleDeckPlayback(deckId: number): DeckState
  setDeckVolume(deckId: number, volume: number): DeckState
  clearDeck(deckId: number): DeckState
}

export interface DeckState {
  id: number
  volume: number
  isPlaying: boolean
  loadedTrack?: string
}

export interface EngineState {
  mixer: MixerState
  decks: Array<DeckState>
}

export declare function getTrackMetadata(filePath: string): TrackMetadata

export interface HotCueMetadata {
  positionSeconds: number
  label?: string
}

export declare function init(): void

export interface MixerState {
  masterVolume: number
  deckChannels: Array<number>
}

export interface TrackMetadata {
  path: string
  title: string
  artist?: string
  bpm?: number
  durationSeconds?: number
  hotCues: Array<HotCueMetadata>
}

export interface TrackMetadataUpdate {
  title?: string
  artist?: string
  bpm?: number
  hotCues?: Array<HotCueMetadata>
}

export declare function updateTrackMetadata(filePath: string, updates: TrackMetadataUpdate): TrackMetadata
